// auto-generated
[<AutoOpen>]
module En3Tho.FSharp.Extensions.AspNetCore.WebAppExtensions

open System
open Microsoft.AspNetCore.Builder

type WebApplication with
    member inline this.MapGet(pattern, func: Action) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'TResult>) = this.MapGet(pattern, handler = func)
    member inline this.MapGet(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'T16, 'TResult>) = this.MapGet(pattern, handler = func)

    member inline this.MapPost(pattern, func: Action) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'TResult>) = this.MapPost(pattern, handler = func)
    member inline this.MapPost(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'T16, 'TResult>) = this.MapPost(pattern, handler = func)

    member inline this.MapPut(pattern, func: Action) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'TResult>) = this.MapPut(pattern, handler = func)
    member inline this.MapPut(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'T16, 'TResult>) = this.MapPut(pattern, handler = func)

    member inline this.MapDelete(pattern, func: Action) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'TResult>) = this.MapDelete(pattern, handler = func)
    member inline this.MapDelete(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'T16, 'TResult>) = this.MapDelete(pattern, handler = func)

    member inline this.MapPatch(pattern, func: Action) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'TResult>) = this.MapPatch(pattern, handler = func)
    member inline this.MapPatch(pattern, func: Func<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7, 'T8, 'T9, 'T10, 'T11, 'T12, 'T13, 'T14, 'T15, 'T16, 'TResult>) = this.MapPatch(pattern, handler = func)